### ISSUE TITLE
str object has no attribute package.

### ISSUE THREAD

**Issue by hvdklauw** [novafloss/raincoat#1]
```
Traceback (most recent call last):
  File "/venv/bin/raincoat", line 11, in <module>
    sys.exit(main())
  File "/venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/venv/lib/python3.5/site-packages/raincoat/__init__.py", line 24, in main
    "(from {match.filename}:{match.lineno})".format(match=match))
AttributeError: 'str' object has no attribute 'package'
```

The Raincoat.add_error does:
```python
self.errors.append((error, match))
```

But the command does:
```python
for match, error in inst.errors:
```

**Comment by ewjoachim** [comment]
oh, that's right... It seems there's still a lack of integration test that validates everything at once without mocking...

I'm on it :)

**Comment by ewjoachim** [comment]
I've reproduced the issue, and fixed it. Plus, a new acceptance test was written so we don't have gross errors like this. 0.2.0 is released with the fix.

 :100: :heavy_multiplication_x: thank you for trying the package ! You rock.

(BTW, if the problem is not solved for you, by all means feel free to re-open).

Have a nice day :)
